backend:
  name: github
  repo: bnj3d-creations/bnj3d-business-site
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Page Body", name: "body", widget: "markdown" }
